### ISSUE TITLE
Add the word "Laravel" to the README

### ISSUE THREAD

**Issue by lehtu** [Vinelab/RSS#7]
Has this been made for Laravel framework or should this work as is?

Just tried to install this via composer to non-framework project and it doesn't work and I don't have any providers array as said in readme: "Edit app.php and add 'Vinelab\Rss\RssServiceProvider', to the 'providers' array."

If this is made for Laravel, it would be nice to mention that in readme file.

**Comment by Mulkave** [comment]
Sorry you had a bad time and thanks for pointing it out. It's been updated to work as a framework-agnostic package so you can simply do the following:

```php
require 'vendor/autoload.php';

use Vinelab\Rss\Rss;

$rss = new Rss();
$rss->feed('...');
```
